services:
  client:
    image: reddit-clone-client:v1.0
    build:
      context: ./client
    container_name: client
    ports:
      - "3000:3000"
    networks:
      - front
    depends_on:
      - server

  server:
    image: reddit-clone-server:v1.0
    build:
      context: ./server
    container_name: server
    ports:
      - "8080:8080"
    networks:
      - front
      - back
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: database
    ports:
      - "27017:27017"
    networks:
      - back
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}

networks:
  front:
  back:
